name: koha-mono
services:
    koha:
        build: ./services/koha
        hostname: "${KOHA_INSTANCE}${KOHA_DOMAIN}"
        tmpfs:
            - /cover_db
            - /tmp
        env_file:
            - .env
        networks:
            kohanet:
                aliases:
                    - "${KOHA_INSTANCE}${KOHA_INTRANET_SUFFIX}${KOHA_DOMAIN}"
                    - "${KOHA_INSTANCE}${KOHA_DOMAIN}"
        depends_on:
            memcached:
                condition: service_healthy
        ports:
            - "8080:8080"
            - "8081:8081"
            - "3306:3306"
    
    memcached:
        image: memcached
        command: memcached -m 64m
        networks:
            - kohanet
        healthcheck:
            test: ["CMD-SHELL", "/bin/bash -c 'exec 3<>/dev/tcp/localhost/11211; printf \"stats\nquit\n\" >&3'"]
            interval: 10s
            start_period: "2m"
            start_interval: "5s"

networks:
    kohanet: